FROM python:3.12-slim

# Set environment variables for Uvicorn configuration
ENV HOST=0.0.0.0
ENV PORT=8000

WORKDIR /app

# Install Poetry

RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi

# Copy your application code
COPY . .

EXPOSE $PORT

# Use CMD to start the FastAPI server via Uvicorn, using environment variables
CMD gunicorn -w 3 -k uvicorn.workers.UvicornWorker app.main:app  --bind 0.0.0.0:8000 --preload --log-level=debug --timeout 120
